name: Update TryHackMe Badge

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"   # runs every 12 hours

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download TryHackMe badge
        run: |
          curl -o assets/thm-badge.png https://tryhackme-badges.s3.amazonaws.com/VigneshXploit.png

      - name: Commit and push badge if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add assets/thm-badge.png
          git diff --quiet && git diff --staged --quiet || git commit -m "Updated TryHackMe badge"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
