name: Update TryHackMe Badge

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download TryHackMe badge
        run: |
          curl -o assets/thm-badge.png https://tryhackme-badges.s3.amazonaws.com/VigneshXploit.png

      - name: Commit and push badge if changed
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Updated TryHackMe badge"
          add: "assets/thm-badge.png"
