name: Update TryHackMe Badge

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download TryHackMe badge
        run: |
          mkdir -p assets
          curl -L -o assets/thm-badge.png https://tryhackme-badges.s3.amazonaws.com/VigneshXploit.png

      - name: Commit and push badge if changed
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add assets/thm-badge.png
          git diff --quiet && git diff --staged --quiet || git commit -m "Updated TryHackMe badge"

          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
