name: Update TryHackMe Badge

on:
  schedule:
    - cron: '0 0 * * *'    # Runs every day at midnight
  workflow_dispatch:        # Allows manual triggering

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch TryHackMe Badge
        uses: DhanushNehru/tryhackme-badge-action-workflow@v1.1
        with:
          image_path: './assets/tryhackme-badge.png'
          username: 'VigneshXploit'
          user_id: '4241178'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
